---
# tasks file for ansible-arch-keyserver

- name: Create user's .gnupg directory
  file:
    path: /home/{{ ansible_env.USER }}/.gnupg
    state: directory
    owner: '{{ ansible_env.USER }}'
    group: '{{ ansible_env.USER }}'
    mode: 0700

- name: Create gpg.conf
  lineinfile:
    path: /home/{{ ansible_env.USER }}/.gnupg/gpg.conf
    line: 'keyserver hkps://keyserver.ubuntu.com'
    create: yes
    owner: '{{ ansible_env.USER }}'
    group: '{{ ansible_env.USER }}'
    mode: 0600
